// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Serve provides a mock function with given fields:
func (_m *Handler) Serve() {
	_m.Called()
}
