// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Usecaser is an autogenerated mock type for the Usecaser type
type Usecaser struct {
	mock.Mock
}

// Minus provides a mock function with given fields: _a0, _a1
func (_m *Usecaser) Minus(_a0 int, _a1 int) int {
	ret := _m.Called(_a0, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Plus provides a mock function with given fields: _a0, _a1
func (_m *Usecaser) Plus(_a0 int, _a1 int) int {
	ret := _m.Called(_a0, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
