// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Utilize is an autogenerated mock type for the Utilize type
type Utilize struct {
	mock.Mock
}

// CheckArgument provides a mock function with given fields: argumentPlace
func (_m *Utilize) CheckArgument(argumentPlace int) bool {
	ret := _m.Called(argumentPlace)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(argumentPlace)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// DisplayMenu provides a mock function with given fields:
func (_m *Utilize) DisplayMenu() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *Utilize) Reset() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
